#!/bin/sh
#
#
if [ -f /swapfile ];then
   # it has swap
   echo has swap
   cat /proc/swaps
else
   echo we would like to add a swapfile
   echo you will be asked to type the curated password
   echo
   sudo fallocate -l 1G /swapfile
   sudo chmod 600 /swapfile
   sudo mkswap /swapfile
   sudo swapon /swapfile
fi

cd $HOME
if [ -d curated-demo ];then
  git -C $HOME/curated-demo pull
else
  echo missing curated demo dir
  echo re-cloning
  git clone https://github.com/brad73435/curated-demo
fi

mkdir -p $HOME/bin
cp $HOME/curated-demo/curated-update $HOME/bin
cp $HOME/curated-demo/mininet.sh $HOME/bin
cp $HOME/curated-demo/webvarcli $HOME/bin
cp $HOME/curated-demo/dot-bashrc $HOME/.bashrc

if [ -z "`pgrep gns3`" ];then
 echo no GNS seen running
 echo updating docker images
 docker pull ghcr.io/tatarsky/gns3/controllerprod:0.1
 docker pull ghcr.io/tatarsky/gns3/openvswitch28:0.1
 docker pull ghcr.io/tatarsky/gns3/cnhost:0.1
 docker pull ghcr.io/tatarsky/gns3/router:0.1
 docker images
else
 echo GNS3 appears to be still running
 echo Please quit it and re-run curated-update
fi
