#!/bin/sh
VER=0.2
docker images
docker pull ghcr.io/tatarsky/gns3/controllerprod:$VER
docker pull ghcr.io/tatarsky/gns3/controllerqos:$VER
docker pull ghcr.io/tatarsky/gns3/openvswitch28:$VER
docker pull ghcr.io/tatarsky/gns3/cnhost:$VER
docker pull ghcr.io/tatarsky/gns3/router:$VER
